name: Issue to PR

on:
  issues:
    types: [opened]

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub App token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.QUERY_GUARDIAN_APP_ID }}
          private-key: ${{ secrets.QUERY_GUARDIAN_PRIVATE_KEY }}

      - name: Run queryvibe Docker image
        run: |
          mkdir -p data
          docker run --rm -v ${{ github.workspace }}/data:/app/data \
            -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            ruigomes99/queryvibe:latest

      - name: Print query_path from remediation.json
        run: |
          cat data/suggestion/remediation.json
          query_path=$(jq -r '.query_path' data/suggestion/remediation.json)
          echo "query_path: $query_path"

      - name: Create dummy file
        run: |
          echo "This is a dummy file for issue #${{ github.event.issue.number }}" > dummy.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.app-token.outputs.token }}
          commit-message: "Add dummy file for issue #${{ github.event.issue.number }}"
          title: "PR for issue #${{ github.event.issue.number }}"
          body: "Automatically created PR for issue #${{ github.event.issue.number }}"
          branch: "issue-${{ github.event.issue.number }}"
          base: ${{ github.event.repository.default_branch }}
