name: create-fix-for-issue

on:
  issues:
    types: [opened]

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub App token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.QUERY_GUARDIAN_APP_ID }}
          private-key: ${{ secrets.QUERY_GUARDIAN_PRIVATE_KEY }}

      - name: Run queryvibe Docker image
        run: |
          mkdir -p data
          docker run --rm \
            -u "$(id -u):$(id -g)" \
            -v ${{ github.workspace }}/data:/app/data \
            -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            ruigomes99/queryvibe:latest github

      - name: Replace query.rego with generated one
        run: |
          query_path=$(jq -r '.query_path' data/suggestion/remediation.json)
          echo "Replacing $query_path/query.rego with generated file"
          cp data/suggestion/query.rego "$query_path/query.rego"

      - name: Remove data folder
        run: rm -rf data

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.app-token.outputs.token }}
          commit-message: "fix issue #${{ github.event.issue.number }}"
          title: "fix(queries): PR for issue #${{ github.event.issue.number }}"
          body: >
            Closes #${{ github.event.issue.number }}

            # fix(query): PR for issue #${{ github.event.issue.number }}

            - Automatically created PR.


            I submit this contribution under the Apache-2.0 license.
          branch: "issue-${{ github.event.issue.number }}"
          base: ${{ github.event.repository.default_branch }}
