name: Issue to PR

on:
  issues:
    types: [opened]

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub App token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.QUERY_GUARDIAN_APP_ID }}
          private-key: ${{ secrets.QUERY_GUARDIAN_PRIVATE_KEY }}

      - name: Extract query path from issue body
        id: extract
        run: |
          printf '%s\n' "${{ github.event.issue.body }}" > issue_body.txt
          grep -oE '/assets/queries/[^\)\s]+' issue_body.txt | head -n 1 > query_path.txt
          echo "QUERY_PATH=$(cat query_path.txt)" >> $GITHUB_OUTPUT

      - name: Show extracted query path
        run: |
          echo "Extracted QUERY_PATH: ${{ steps.extract.outputs.QUERY_PATH }}"

      - name: Create a dummy file
        run: |
          echo "This is a dummy file for issue #${{ github.event.issue.number }}" > dummy.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.app-token.outputs.token }}
          commit-message: "Add dummy file for issue #${{ github.event.issue.number }}"
          title: "PR for issue #${{ github.event.issue.number }}"
          body: "Automatically created PR for issue #${{ github.event.issue.number }}"
          branch: "issue-${{ github.event.issue.number }}"
          base: ${{ github.event.repository.default_branch }}
