name: Issue to PR

on:
  issues:
    types: [opened]

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub App token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.QUERY_GUARDIAN_APP_ID }}
          private-key: ${{ secrets.QUERY_GUARDIAN_PRIVATE_KEY }}

      - name: Extract query path from issue body
        id: extract
        run: |
          # Save body to a temporary file to avoid shell escaping issues
          echo "${{ github.event.issue.body }}" > issue_body.txt

          # Extract the /assets/queries/... path from the GitHub URL in the body
          QUERY_PATH=$(grep -oE '/assets/queries/[^ )\n\r]+' issue_body.txt | head -n1)

          echo "Extracted path: $QUERY_PATH"

          # Export to environment
          echo "QUERY_PATH=$QUERY_PATH" >> $GITHUB_ENV

      - name: Create a dummy file
        run: |
          echo "This is a dummy file for issue #${{ github.event.issue.number }}" > dummy.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.app-token.outputs.token }}
          commit-message: "Add dummy file for issue #${{ github.event.issue.number }}"
          title: "PR for issue #${{ github.event.issue.number }}"
          body: "Automatically created PR for issue #${{ github.event.issue.number }}"
          branch: "issue-${{ github.event.issue.number }}"
          base: ${{ github.event.repository.default_branch }}
