name: cronjob-queryvibe

on:
  schedule:
    - cron: '0 0 * * *'   # Runs every day at midnight UTC
  workflow_dispatch:      # Allows manual trigger

jobs:
  iac-scraping-and-generate-fixes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub App token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.QUERY_GUARDIAN_APP_ID }}
          private-key: ${{ secrets.QUERY_GUARDIAN_PRIVATE_KEY }}

      - name: Run queryvibe Docker image
        run: |
          mkdir -p data
          docker run --rm \
            -u "$(id -u):$(id -g)" \
            -v ${{ github.workspace }}/data:/app/data \
            -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            ruigomes99/queryvibe:latest patchnotes

      - name: Move generated cronJob folder
        run: |
          mv ./data/cronJob .

      - name: Remove data folder
        run: rm -rf data

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.app-token.outputs.token }}
          commit-message: "chore(cronjob): update Terraform AWS queries"
          title: "chore(cronjob): update Terraform AWS queries"
          body: >
            # chore(cronjob): update Terraform AWS queries

            - Automatically created PR.


            I submit this contribution under the Apache-2.0 license.
          branch: "cronjob-update-$(date +%Y%m%d%H%M%S)"
          base: ${{ github.event.repository.default_branch }}
